In [2]:
import pandas as pd
import time
import pickle5 as pickle
import sys
import os
import torch
from PIL import Image, ImageDraw
sys.path.append('../src')

from utils import masking_generator, utils

/home/is/hikaru-si/.pyenv/versions/3.8.6/envs/exp_005/lib/python3.8/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [3]:
file_names = os.listdir("../data/preprocessing_shared/10000_split/")
file_names[4:]

['40000.pkl',
 '50000.pkl',
 '60000.pkl',
 '70000.pkl',
 '80000.pkl',
 '90000.pkl',
 '100000.pkl',
 '110000.pkl',
 '120000.pkl',
 '130000.pkl',
 '140000.pkl',
 '150000.pkl',
 '160000.pkl',
 '170000.pkl',
 '180000.pkl']

In [ ]:
df_from_pkl = pd.read_pickle('../data/preprocessing_shared/encoded_dataset_mim_30000.pkl')

In [3]:
len(df_from_pkl)

NameError: name 'df_from_pkl' is not defined

In [4]:
start = time.time()
with open("../data/preprocessing_shared/wpa_10000/20000.pkl", 'rb') as f:
    data = pickle.load(f)
t = time.time() - start
print(len(data), flush=True)

23419


In [6]:
len(data)

23419

In [48]:
data[1]["alignment_labels"]

tensor([ True, False, False, False, False,  True,  True,  True,  True,  True,
         True,  True, False, False, False, False, False, False, False, False,
        False, False, False,  True,  True,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False,  True,  True,
         True, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False,  True, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
         True, False, False, False, False, False, False, False, False, False,
        False, False,  True,  True, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, 

In [46]:
a = torch.nn.utils.rnn.pad_sequence(
      [b["alignment_labels"] for b in data[3:5]],
      batch_first=True,
      padding_value=False
  )

In [47]:
a.dtype

torch.bool

In [ ]:
    my_dataloader = My_DataLoader.My_Dataloader(vocab)
    train_dataloader = my_dataloader(train_data, batch_size=args.batch_size, shuffle=False)

In [22]:
data[1]["alignment_labels"]

torch.Size([173])

In [12]:
torch.stack([data[0]["alignment_labels"], data[1]["alignment_labels"]])

RuntimeError: stack expects each tensor to be equal size, but got [512] at entry 0 and [173] at entry 1

In [17]:
data_1[-1].keys()

dict_keys(['input_ids', 'bbox', 'pixel_values', 'label', 'bool_masked_pos', 'alignment_labels'])

In [8]:
data[-1].keys()

dict_keys(['input_ids', 'bbox', 'pixel_values', 'label', 'bool_masked_pos', 'alignment_labels'])

In [10]:
with open(f"../data/preprocessing_shared/wpa_10000/test.pkl", 'wb') as f:
    pickle.dump(data, f, protocol=5)

In [3]:
len(data)

23274

In [6]:
len(data), data[0].keys(), data[-1].keys()

(23274,
 dict_keys(['input_ids', 'bbox', 'pixel_values', 'label', 'bool_masked_pos', 'alignment_labels']),
 dict_keys(['input_ids', 'bbox', 'pixel_values', 'label', 'bool_masked_pos', 'alignment_labels']))

In [36]:
data[-1]["bool_masked_pos"].shape

torch.Size([1, 196])

In [22]:
visual_bbox = utils.init_visual_bbox()
visual_bbox.shape

torch.Size([196, 4])

In [34]:
visual_bbox[-1]

tensor([ 928,  928, 1000, 1000])

In [40]:
visual_bbox[data[-1]["bool_masked_pos"][0]].shape

torch.Size([75, 4])

In [53]:
data[-1]["alignment_labels"].sum()

tensor(12)

In [57]:
bbox = torch.tensor(data[-1]["bbox"])

In [60]:
bbox[data[-1]["alignment_labels"]][0]

tensor([0, 0, 0, 0])

In [66]:
data[-1]["alignment_labels"].shape

torch.Size([194])

In [54]:
data[-1]["bbox"][data[-1]["alignment_labels"]]

TypeError: only integer tensors of a single element can be converted to an index

In [49]:
data[-1]["bbox"][data[-1]["alignment_labels"][0]]

AttributeError: 'list' object has no attribute 'shape'

In [73]:
rect = Image.new("RGBA", (1000, 1000), (0, 0, 255))
rect_d = ImageDraw.Draw(rect)
for b in data[2]["bbox"]:
    rect_d.rectangle(b, outline=(0, 255, 225))
for b in visual_bbox[data[2]["bool_masked_pos"][0]]:
    rect_d.rectangle(list(b))
bbox = torch.tensor(data[2]["bbox"])
for b in bbox[data[2]["alignment_labels"]]:
    rect_d.rectangle(list(b), outline=(225, 0, 225), width=3)
rect.show()
rect.save("bboxes.png")

Error: no "view" mailcap rules found for type "image/png"


In [72]:
data[-1]["bool_masked_pos"][0]

tensor([False, False, False, False, False, False, False, False, False, False,
         True,  True,  True,  True, False, False, False, False, False, False,
        False, False, False, False,  True,  True,  True,  True, False, False,
        False, False, False, False, False, False, False, False,  True,  True,
         True,  True, False, False, False, False, False, False, False, False,
        False, False,  True,  True,  True,  True, False, False, False, False,
        False, False,  True,  True,  True,  True,  True, False, False, False,
        False, False, False, False, False, False,  True,  True,  True,  True,
         True, False, False, False, False, False, False, False, False, False,
         True,  True,  True,  True,  True, False, False, False, False, False,
        False, False, False, False,  True,  True,  True,  True,  True,  True,
         True,  True, False, False, False, False, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True, False, False, 

In [5]:
sys.getsizeof(data)

198104

In [64]:
len(data[-1]["input_ids"])

194

In [6]:
start = time.time()
with open("../data/preprocessing_shared/30000data_10000_split/0.pkl", 'rb') as f:
    data = pickle.load(f)
t = time.time() - start
print(len(data), flush=True)

23274


In [7]:
sys.getsizeof(data)

198104

In [1]:
data = list((range(15)))

In [4]:
data, len(data)

([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14], 15)

In [14]:
for i in range(0, 15, 4):
  print(data[i: i+4])

[0, 1, 2, 3]
[4, 5, 6, 7]
[8, 9, 10, 11]
[12, 13, 14]
