In [1]:
import random

In [13]:
random.seed(42)
for _ in range(10):
    print(random.randint(0, 10))
state = random.getstate()

10
1
0
4
3
3
2
1
10
8


In [15]:
for _ in range(10):
    random.seed(42)
    print(random.randint(0, 10))

10
10
10
10
10
10
10
10
10
10


In [17]:
random.setstate(state)
for _ in range(10):
    print(random.randint(0, 10))
state = random.getstate()

9
6
0
0
1
3
3
8
9
0


In [18]:
from random import Random
randoms = [Random(i) for i in range(10)]

In [19]:
randoms

In [28]:
random_1 = Random(1)
for _ in range(10):
    print(random_1.randint(0, 10))

2
9
1
4
1
7
7
7
10
6


In [29]:
random_2 = Random(1)
for _ in range(5):
    print(random_2.randint(0, 10))

2
9
1
4
1


In [30]:
for _ in range(5):
    print(random_1.randint(0, 10))

3
1
7
0
6


In [31]:
for _ in range(5):
    print(random_2.randint(0, 10))

7
7
7
10
6


In [95]:
import contextlib
import numpy as np
import numpy as npp

@contextlib.contextmanager
def temp_seed(seed):
    state = np.random.get_state()
    np.random.seed(seed)
    try:
        yield
    finally:
        np.random.set_state(state)

In [96]:
np.random.seed(0)

In [97]:
print(np.random.randn(3))
print(np.random.randn(3))

[1.76405235 0.40015721 0.97873798]
[ 2.2408932   1.86755799 -0.97727788]


In [101]:
npp.random.seed(0)

In [102]:
npp.random.randn(3)

array([1.76405235, 0.40015721, 0.97873798])

In [103]:
def gene_rand():
  for _ in range(3):
    print(npp.random.randn(3))

In [104]:
with temp_seed(5):
     gene_rand()

[ 0.44122749 -0.33087015  2.43077119]
[-0.25209213  0.10960984  1.58248112]
[-0.9092324  -0.59163666  0.18760323]


In [105]:
npp.random.randn(3)

array([ 2.2408932 ,  1.86755799, -0.97727788])

In [54]:
with temp_seed(5):
    np_1 = np.random
    # print(np.random.randn(3))
    # print(np.random.randn(3)) 

In [55]:
print(np_1.randn(3))
print(np_1.randn(3))

[ 0.95008842 -0.15135721 -0.10321885]
[0.4105985  0.14404357 1.45427351]


In [56]:
np.random.randn(3)

array([0.76103773, 0.12167502, 0.44386323])

In [88]:
@contextlib.contextmanager
def temp_random_seed(seed):
    state = random.getstate()
    random.seed(seed)
    try:
        yield
    finally:
        random.setstate(state)

In [89]:
import random

In [90]:
random.seed(1)

In [91]:
print(random.randint(0, 100))
print(random.randint(0,100))

17
72


In [92]:
random.seed(1)
random.randint(0, 100)

17

In [93]:
with temp_random_seed(4):
  print(random.randint(0, 100))
  print(random.randint(0,100))
  

30
38


In [94]:
random.randint(0, 100)

72